version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g @angular/cli@17
      - apt-get update
      - apt-get install -y chromium-browser
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - ng test --no-watch --no-progress --browsers=ChromeHeadlessCI --code-coverage
